2021-04-18 21:30:00,513 INFO    Thread-3  :16176 [wandb_setup.py:_flush():69] setting env: {'project': 'simpledrawer-ddqn_random_start_fixed_line_pos', 'entity': 'riccir', 'root_dir': '/home/antoniopioricciardi/PycharmProjects/simpledrawer', 'sweep_id': 'gcfron8m', 'run_id': 'gfiapkl4', 'sweep_param_path': '/home/antoniopioricciardi/PycharmProjects/simpledrawer/wandb/sweep-gcfron8m/config-gfiapkl4.yaml'}
2021-04-18 21:30:00,513 INFO    Thread-3  :16176 [wandb_setup.py:_flush():69] setting login settings: {}
2021-04-18 21:30:00,513 INFO    Thread-3  :16176 [wandb_init.py:_log_setup():336] Logging user logs to /home/antoniopioricciardi/PycharmProjects/simpledrawer/wandb/run-20210418_213000-gfiapkl4/logs/debug.log
2021-04-18 21:30:00,513 INFO    Thread-3  :16176 [wandb_init.py:_log_setup():337] Logging internal logs to /home/antoniopioricciardi/PycharmProjects/simpledrawer/wandb/run-20210418_213000-gfiapkl4/logs/debug-internal.log
2021-04-18 21:30:00,513 INFO    Thread-3  :16176 [wandb_init.py:init():369] calling init triggers
2021-04-18 21:30:00,513 INFO    Thread-3  :16176 [wandb_init.py:init():374] wandb.init called with sweep_config: {'batch_size': 32, 'fc_layer_size': 128, 'gamma': 0.6, 'learning_rate': 0.001}
config: {'replace': 1000, 'learning_rate': 0.001, 'gamma': 0.6, 'epsilon': 0.7, 'epsilon_min': 0.0, 'epsilon_dec': 1e-05, 'mem_size': 50000, 'batch_size': 32, 'optimizer': 'adam', 'fc_layer_size': 128, 'max_steps': 200000}
2021-04-18 21:30:00,513 INFO    Thread-3  :16176 [wandb_init.py:init():418] starting backend
2021-04-18 21:30:00,514 INFO    Thread-3  :16176 [backend.py:_multiprocessing_setup():69] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2021-04-18 21:30:00,519 INFO    Thread-3  :16176 [backend.py:ensure_launched():123] starting backend process...
2021-04-18 21:30:00,522 INFO    Thread-3  :16176 [backend.py:ensure_launched():127] started backend process with pid: 16214
2021-04-18 21:30:00,523 INFO    Thread-3  :16176 [wandb_init.py:init():423] backend started and connected
2021-04-18 21:30:00,524 INFO    Thread-3  :16176 [wandb_run.py:_config_callback():749] config_cb None None {'batch_size': 32, 'fc_layer_size': 128, 'gamma': 0.6, 'learning_rate': 0.001}
2021-04-18 21:30:00,524 INFO    Thread-3  :16176 [wandb_init.py:init():463] updated telemetry
2021-04-18 21:30:00,524 INFO    Thread-3  :16176 [wandb_init.py:init():482] communicating current version
2021-04-18 21:30:01,012 INFO    Thread-3  :16176 [wandb_init.py:init():487] got version response upgrade_message: "wandb version 0.10.26 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2021-04-18 21:30:01,012 INFO    Thread-3  :16176 [wandb_init.py:init():495] communicating run to backend with 30 second timeout
2021-04-18 21:30:02,386 INFO    Thread-3  :16176 [wandb_init.py:init():520] starting run threads in backend
2021-04-18 21:30:02,412 INFO    Thread-3  :16176 [wandb_run.py:_console_start():1524] atexit reg
2021-04-18 21:30:02,412 INFO    Thread-3  :16176 [wandb_run.py:_redirect():1371] redirect: SettingsConsole.REDIRECT
2021-04-18 21:30:02,412 INFO    Thread-3  :16176 [wandb_run.py:_redirect():1376] Redirecting console.
2021-04-18 21:30:02,413 ERROR   Thread-3  :16176 [wandb_run.py:_redirect():1441] Failed to redirect.
Traceback (most recent call last):
  File "/home/antoniopioricciardi/PycharmProjects/simpledrawer/venv/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 1434, in _redirect
    out_redir.install()
  File "/home/antoniopioricciardi/PycharmProjects/simpledrawer/venv/lib/python3.8/site-packages/wandb/sdk/lib/redirect.py", line 605, in install
    _WSCH.add_fd(self._pipe_read_fd)
  File "/home/antoniopioricciardi/PycharmProjects/simpledrawer/venv/lib/python3.8/site-packages/wandb/sdk/lib/redirect.py", line 555, in add_fd
    self._register()
  File "/home/antoniopioricciardi/PycharmProjects/simpledrawer/venv/lib/python3.8/site-packages/wandb/sdk/lib/redirect.py", line 540, in _register
    old_handler = signal.signal(signal.SIGWINCH, lambda *_: None)
  File "/usr/lib/python3.8/signal.py", line 47, in signal
    handler = _signal.signal(_enum_to_int(signalnum), _enum_to_int(handler))
ValueError: signal only works in main thread
2021-04-18 21:30:02,413 INFO    Thread-3  :16176 [wandb_init.py:init():544] run started, returning control to user process
2021-04-18 21:30:09,170 INFO    Thread-3  :16176 [wandb_run.py:finish():1167] finishing run riccir/simpledrawer-ddqn_random_start_fixed_line_pos/gfiapkl4
