2021-04-19 13:19:13,616 INFO    Thread-7  :21364 [wandb_setup.py:_flush():69] setting env: {'project': 'simpledrawer-ddqn_random_start_fixed_line_pos', 'entity': 'riccir', 'root_dir': '/home/antoniopioricciardi/PycharmProjects/simpledrawer', 'run_id': '2qte0vcc', 'sweep_param_path': '/home/antoniopioricciardi/PycharmProjects/simpledrawer/wandb/sweep-8y9lg0ab/config-2qte0vcc.yaml', 'sweep_id': '8y9lg0ab'}
2021-04-19 13:19:13,616 INFO    Thread-7  :21364 [wandb_setup.py:_flush():69] setting login settings: {}
2021-04-19 13:19:13,616 INFO    Thread-7  :21364 [wandb_init.py:_log_setup():336] Logging user logs to /home/antoniopioricciardi/PycharmProjects/simpledrawer/wandb/run-20210419_131913-2qte0vcc/logs/debug.log
2021-04-19 13:19:13,616 INFO    Thread-7  :21364 [wandb_init.py:_log_setup():337] Logging internal logs to /home/antoniopioricciardi/PycharmProjects/simpledrawer/wandb/run-20210419_131913-2qte0vcc/logs/debug-internal.log
2021-04-19 13:19:13,617 INFO    Thread-7  :21364 [wandb_init.py:init():369] calling init triggers
2021-04-19 13:19:13,617 INFO    Thread-7  :21364 [wandb_init.py:init():374] wandb.init called with sweep_config: {'batch_size': 32, 'fc_layer_size': 128, 'gamma': 0.9, 'learning_rate': 0.001}
config: {'replace': 1000, 'learning_rate': 0.001, 'gamma': 0.6, 'epsilon': 0.7, 'epsilon_min': 0.0, 'epsilon_dec': 1e-05, 'mem_size': 50000, 'batch_size': 64, 'optimizer': 'adam', 'fc_layer_size': 128, 'max_steps': 300000}
2021-04-19 13:19:13,617 INFO    Thread-7  :21364 [wandb_init.py:init():418] starting backend
2021-04-19 13:19:13,617 INFO    Thread-7  :21364 [backend.py:_multiprocessing_setup():69] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2021-04-19 13:19:13,620 INFO    Thread-7  :21364 [backend.py:ensure_launched():123] starting backend process...
2021-04-19 13:19:13,632 INFO    Thread-7  :21364 [backend.py:ensure_launched():127] started backend process with pid: 21456
2021-04-19 13:19:13,633 INFO    Thread-7  :21364 [wandb_init.py:init():423] backend started and connected
2021-04-19 13:19:13,634 INFO    Thread-7  :21364 [wandb_run.py:_config_callback():749] config_cb None None {'batch_size': 32, 'fc_layer_size': 128, 'gamma': 0.9, 'learning_rate': 0.001}
2021-04-19 13:19:13,635 INFO    Thread-7  :21364 [wandb_init.py:init():463] updated telemetry
2021-04-19 13:19:13,635 INFO    Thread-7  :21364 [wandb_init.py:init():482] communicating current version
2021-04-19 13:19:18,642 ERROR   Thread-7  :21364 [wandb_init.py:init():768] error
Traceback (most recent call last):
  File "/home/antoniopioricciardi/PycharmProjects/simpledrawer/venv/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 742, in init
    run = wi.init()
  File "/home/antoniopioricciardi/PycharmProjects/simpledrawer/venv/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 483, in init
    ret = backend.interface.communicate_check_version(
  File "/home/antoniopioricciardi/PycharmProjects/simpledrawer/venv/lib/python3.8/site-packages/wandb/sdk/interface/interface.py", line 773, in communicate_check_version
    result = self._communicate(rec)
  File "/home/antoniopioricciardi/PycharmProjects/simpledrawer/venv/lib/python3.8/site-packages/wandb/sdk/interface/interface.py", line 533, in _communicate
    return self._communicate_async(rec, local=local).get(timeout=timeout)
  File "/home/antoniopioricciardi/PycharmProjects/simpledrawer/venv/lib/python3.8/site-packages/wandb/sdk/interface/interface.py", line 82, in get
    is_set = self._object_ready.wait(timeout)
  File "/usr/lib/python3.8/threading.py", line 558, in wait
    signaled = self._cond.wait(timeout)
  File "/usr/lib/python3.8/threading.py", line 306, in wait
    gotit = waiter.acquire(True, timeout)
Exception
